api/urls.py
from django.urls import path
from .views import GetRandomQuestion, Answer, HelpSteps, LogAttempt

app_name = 'api'

urlpatterns = [

    path('question', GetRandomQuestion.as_view(), name='random-question'),
    path('answer', Answer.as_view(), name='answer'),
    path('help', HelpSteps.as_view(), name='help-steps'),
    path('attempt', LogAttempt.as_view(), name='attempt')
 ]

app/urls.py
from django.urls import path
from .views import LandingPageView, IndexPageView, ProfilePageView
from django.views.generic.base import TemplateView


app_name = 'app'

urlpatterns = [
    path("", IndexPageView.as_view(), name="index"),
    path("landing/", LandingPageView.as_view(), name="landing"),
    path("profile/", ProfilePageView.as_view(), name="profile"),
    path("hello-vue", TemplateView.as_view(template_name="app/hello-vue.html"), name='hello-vue'),
]

music_theory_api/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar


urlpatterns = [

    # Django admin
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),

    # User management
    path('accounts/', include('allauth.urls')),

    # Local apps
    path("", include("app.urls")),



    path('__debug__/', include(debug_toolbar.urls)),

]

questions/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    class_name = models.CharField(null=False, blank=False, max_length=50, unique=True)
    module_name = models.CharField(null=False, blank=False, max_length=50)

    def __str__(self):
        return f"{self.module_name}.{self.class_name}"


class Tag(models.Model):
    name = models.CharField(null=False, blank=False, max_length=50)
    question = models.ManyToManyField(Question)

    def __str__(self):
        return self.name


class Attempt(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    correct = models.BooleanField(default=False)
    number_correct = models.IntegerField(default=0)
    number_incorrect = models.IntegerField(default=0)
    total_attempts = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user}, {self.question}, {self.correct}"

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    premium_user = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}, {self.user.email}, {self.user.userprofile.premium_user}"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    # pylint: disable=unused-argument
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    # pylint: disable=unused-argument
    instance.userprofile.save()

api/views.py
from django.core.cache import cache
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.contrib.auth.mixins import LoginRequiredMixin
from questions.question_generator import QuestionGenerator
from questions.models import Attempt, Question
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.db.models import F


class GetRandomQuestion(LoginRequiredMixin, APIView):

    def get(self, request):
        question = QuestionGenerator.question_factory()
        data = question.response
        return Response(data)


class Answer(LoginRequiredMixin, APIView):

    def post(self, request):
        try:
            user_answer = request.data['answer']
            answer_key = request.data['key']
            user = request.user
            cached_response = cache.get(answer_key)
            expected_user_id = cached_response.get('user_id')
            if expected_user_id and expected_user_id != user.id:
                return Response("User does not have permission to view this answer", status=status.HTTP_403_FORBIDDEN)
            data = {'correct': user_answer == cached_response['answer'],
                    'correct_answer': cached_response['answer']}
        except Exception:
            return Response("Must supply answer and key", status=status.HTTP_400_BAD_REQUEST)
        return Response(data)

class HelpSteps(LoginRequiredMixin, APIView):

    def post(self, request):
        try:
            question_key = request.data['key']
            cached_response = cache.get(question_key)
            data = cached_response['help_steps']
            expected_question_key = cached_response.get('key')
            if question_key != expected_question_key:
                return Response("The requested resource could not be found but may be available in the future.", status=status.HTTP_404_NOT_FOUND)
        except Exception:
            return Response("Must supply question key", status=status.HTTP_400_BAD_REQUEST)
        return Response(data)


class LogAttempt(LoginRequiredMixin, APIView):
    def post(self, request):
        try:
            user_answer = request.data['answer']
            key = request.data['key']
            user = request.user
            cached_response = cache.get(key)
            class_name = cached_response['class_name']
            correct_answer = cached_response['answer']
            question_instance = get_object_or_404(Question, class_name=class_name)
            user_instance = get_object_or_404(User, username=user)
            user_correct = bool(user_answer == correct_answer)
            attempt = Attempt.objects.create(question=question_instance, user=user_instance, correct=user_correct)
            attempt.total_attempts = F('total_attempts') + 1
            attempt.save()
            if user_correct:
                attempt.number_correct = F('number_correct') + 1
                attempt.save()
            else:
                attempt.number_incorrect = F('number_incorrect') + 1
                attempt.save()



        except Exception:
            return Response("I'm sorry, we could not process your request", status=status.HTTP_400_BAD_REQUEST)
        return Response()

app/views.py
from django.views.generic import View
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

# for all views that require user to be logged in, use LoginRequiredMixin


class LandingPageView(View):

    def get(self, request):
        return render(request, 'app/landing.html')

class IndexPageView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'app/questions.html')

class ProfilePageView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'app/profile.html')

app/templates/app/_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="{% static 'app/images/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!--    Google Handrwriting Font-->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Indie+Flower">
    <!--    axios -->
    <!--    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>-->
    <!-- our native styles -->
    <link rel="stylesheet" href="{% static 'app/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

    <title>{% block title %} TheoryDojo {% endblock title %}</title>
</head>
<body>
{% block navbar %}
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
    {% if user.is_authenticated %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="navbar-brand" href="{% url 'account_logout' %}">Logout</a>
        </li>
        <li class="nav-item">
            <a class="navbar-brand" href="{% url 'app:profile' %}">Profile</a>
        </li>
        <li class="nav-item">
            <a class="navbar-brand" href="{% url 'app:index' %}">Random Question</a>
        </li>
    </ul>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% else %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
        </li>
    </ul>
    {% endif %}
    <div class="ml-auto" id="logo-div">
        <img class="logo" src="{% static 'app/images/logo.png' %}" alt="logo">
    </div>
</nav>
{% endblock %}
<div class="container">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

app/templates/app/hello-vue.html
{% extends 'app/_base.html' %}
{% load static %}

{% block content %}
<h1 class="text-muted">HTML Content outside Vue app 'PARENT'</h1>
<div id="hello" class="container"></div>
<script src="{% static 'index-bundle.js' %}"></script>

{% endblock content %}

app/templates/app/landing.html
{% extends 'app/_base.html' %}
{% load static %}


{% block content %}
<h1> TheoryDojo </h1>

{% endblock content %}

app/templates/app/profile.html
{% extends 'app/_base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

<h2>{{ user.username }}'s Profile:</h2>
<li>Email: {{ user.email }}</li>
<li>Premium Status: {{ user.userprofile.premium_user }}</li>
<a class="nav-link" href="{% url 'account_change_password' %}">Change Account Password</a>
{% endblock content %}

app/templates/app/questions.html
{% extends 'app/_base.html' %}
{% load static %}


{% block content %}
<!-- any Django or other non Vue stuff here -->

<h1 class="text-muted" id="questions">Questions</h1>

<!-- import Questions Vue App -->
<div id="question" class="container">
    <div id="loading-wrapper">
        <div id="loading-text">LOADING</div>
        <div id="loading-content"></div>
    </div>
</div>


<script src="{% static 'index-bundle.js' %}"></script>

{% endblock content %}